### ISSUE TITLE
Dat upstream bugs

### ISSUE THREAD

**Issue by pfrazee** [pfrazee/beaker#44]
There are a couple bugs that I'll need upstream help solving. They are:

 - [ ] https://github.com/mafintosh/hyperdrive/issues/87. This issue keeps beaker from being able to open archives created by dat.land.
 - [x] https://github.com/mafintosh/hyperdrive/issues/93. This issue keeps beaker from opening static dats.
 - [x] https://github.com/maxogden/dat/issues/503. Dat stops sharing after a period

**Comment by mafintosh** [comment]
#93 is fixed. Two to go

**Comment by mafintosh** [comment]
#87 is fixed by dat.land updating hyperdrive.

**Comment by mafintosh** [comment]
i have trouble reproducing maxogden/dat#503

**Comment by pfrazee** [comment]
Almost there!

**Comment by mafintosh** [comment]
i'll try to bump the dat.land team to fix the remaining one

**Comment by pfrazee** [comment]
Going to go ahead and close this
